/*
 * Created on 2017-01-30 ( Date ISO 2017-01-30 - Time 11:41:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.impl.jdbc.commons;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Properties;

import javax.sql.DataSource;

import org.junit.Assert;
import org.junit.Test;



/**
 * JUnit tests for DataSourceProvider
 * 
 * @author Telosys 
 *
 */
public class DataSourceProviderTest {

	private void printProperty(Properties properties, String name) {
		String value = properties.getProperty(name);
		System.out.println(" . " + name + " = " + value );
		Assert.assertNotNull( value );
		Assert.assertFalse( "".equals(value.trim()));
	}

	@Test
	public void test1JdbcProperties() throws SQLException {
		System.out.println("--- test JDBC properties");
    	
		System.out.println("JDBC properties file name = '" + DataSourceProvider.getJdbcPrpertiesFileName() + "'");
		System.out.println(" properties file searched via classpath in : " );
		System.out.println(" 1 - 'src/test/resources' " );
		System.out.println(" 2 - 'src/main/resources' " );
		
		Properties properties = DataSourceProvider.loadJdbcPropertiesFromClassPath();

		System.out.println("JDBC properties values : " );
		printProperty(properties, "jdbc.url" );
		printProperty(properties, "jdbc.driverClassName" );
		printProperty(properties, "jdbc.username" );
		printProperty(properties, "jdbc.password" );		
	}
	
	@Test
	public void test2DataSource() throws SQLException {
    	System.out.println("--- test DataSourceProvider ");
    	
    	DataSource dataSource = DataSourceProvider.getDataSource();
    	System.out.println("DataSource ready. ");
    	
    	Connection c = dataSource.getConnection();
    	System.out.println("Connection ready. ");
    	
    	Assert.assertNotNull( c );
    	
    	c.close();
    	System.out.println("Connection closed. ");
	}
}
