/*
 * Java bean class for entity "Driver" 
 * Created on 2017-01-30 ( Date ISO 2017-01-30 - Time 10:02:24 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package org.demo.basic.bean;

import java.io.Serializable;


/**
 * Java bean for entity "Driver"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Driver implements Serializable
{
    private static final long serialVersionUID = 1L;

    private int        id           ; // Id or Primary Key

    private String     nom          ;

    /**
     * Default constructor
     */
    public Driver() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "", NotNull : true ) 
     * @param id
     */
	public void setId( int id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "", NotNull : true ) 
     * @return the field value
     */
	public int getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
    //----------------------------------------------------------------------
    /**
     * Set the "nom" field value
     * This field is mapped on the database column "nom" ( type "", NotNull : true ) 
     * @param nom
     */
    public void setNom( String nom ) {
        this.nom = nom;
    }
    /**
     * Get the "nom" field value
     * This field is mapped on the database column "nom" ( type "", NotNull : true ) 
     * @return the field value
     */
    public String getNom() {
        return this.nom;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(nom);
        return sb.toString(); 
    } 

}
