/*
 * Created on 2017-01-30 ( Date ISO 2017-01-30 - Time 11:40:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import javax.inject.Named;


import org.demo.data.record.CarRecord ;
import org.demo.persistence.CarPersistence;
import org.demo.persistence.impl.jdbc.commons.GenericDAO;

/**
 * Car persistence implementation 
 * 
 * @author Telosys
 *
 */
@Named("CarPersistence")
public class CarPersistenceJdbc extends GenericDAO<CarRecord> implements CarPersistence {

	private final static String SQL_SELECT_ALL = 
		"select id, nom, driver from Car"; 

	private final static String SQL_SELECT = 
		"select id, nom, driver from Car where id = ?";

	private final static String SQL_INSERT = 
		"insert into Car ( id, nom, driver ) values ( ?, ?, ? )";

	private final static String SQL_UPDATE = 
		"update Car set nom = ?, driver = ? where id = ?";

	private final static String SQL_DELETE = 
		"delete from Car where id = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from Car";

	private final static String SQL_COUNT = 
		"select count(*) from Car where id = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public CarPersistenceJdbc() {
		super();
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, CarRecord car) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, car.getId() ) ; // "id" : int
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, CarRecord car) throws SQLException {
		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, car.getId() ) ; // "id" : int
		setValue(ps, i++, car.getNom() ) ; // "nom" : java.lang.String
		setValue(ps, i++, car.getDriver() ) ; // "driver" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, CarRecord car) throws SQLException {
		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, car.getNom() ) ; // "nom" : java.lang.String
		setValue(ps, i++, car.getDriver() ) ; // "driver" : java.lang.Integer
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, car.getId() ) ; // "id" : int
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param id;
	 * @return the new instance
	 */
	private CarRecord newInstanceWithPrimaryKey( Integer id ) {
		CarRecord car = new CarRecord();
		car.setId( id );
		return car ;
	}

	//----------------------------------------------------------------------
	@Override
	protected CarRecord newInstance() {
		return new CarRecord() ;
	}

    //----------------------------------------------------------------------
	@Override
	protected CarRecord populateBean(ResultSet rs, CarRecord car) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		car.setId(rs.getInt("id")); // int
		car.setNom(rs.getString("nom")); // java.lang.String
		car.setDriver(rs.getInt("driver")); // java.lang.Integer
		if ( rs.wasNull() ) { car.setDriver(null); }; // not primitive number => keep null value if any
		return car ;
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public CarRecord findById( Integer id ) {
		CarRecord car = newInstanceWithPrimaryKey( id ) ;
		if ( super.doSelect(car) ) {
			return car ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public List<CarRecord> findAll() {
		return super.doSelectAll();
	}

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param car
	 * @return true if found, false if not found
	 */
	//@Override
	public boolean load( CarRecord car ) {
		return super.doSelect(car) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param car
	 */
	public long insert(CarRecord car) {
		super.doInsert(car);
		return 0L ;
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public CarRecord create(CarRecord car) {
		insert(car);
		return car ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public boolean update(CarRecord car) {
		int r = super.doUpdate(car);
		return r > 0 ;

	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public CarRecord save(CarRecord car) {
		if ( super.doExists(car) ) {
			super.doUpdate(car);
		}
		else {
			super.doInsert(car);
		}
		return car ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public boolean deleteById( Integer id ) {
		CarRecord car = newInstanceWithPrimaryKey( id ) ;
		int r = super.doDelete(car);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public boolean delete( CarRecord car ) {
		int r = super.doDelete(car);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param id;
	 * @return
	 */
	// @Override
	public boolean exists( Integer id ) {
		CarRecord car = newInstanceWithPrimaryKey( id ) ;
		return super.doExists(car);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param car
	 * @return
	 */
	// @Override
	public boolean exists( CarRecord car ) {
		return super.doExists(car);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	// @Override
	public long count() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelectAll() {
		return SQL_SELECT_ALL;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

}
