/*
 * Created on 2017-01-30 ( Date ISO 2017-01-30 - Time 10:04:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.data.record;


import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean CarRecord
 * 
 * @author Telosys Tools Generator
 *
 */
public class CarRecordTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class CarRecord getters and setters ..." );
		
		CarRecord carRecord = new CarRecord();


		//--- Test setter/getter for attribute "id"  ( model type : int / wrapperType : Integer )
		carRecord.setId( 100 ) ;
		Assert.assertTrue(  100 == carRecord.getId()  ) ; // Primitive type in model


		//--- Test setter/getter for attribute "nom"  ( model type : String / wrapperType : String )
		carRecord.setNom( "A" ) ;
		Assert.assertEquals( "A", carRecord.getNom() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "driver"  ( model type : Integer / wrapperType : Integer )
		carRecord.setDriver( Integer.valueOf(100) ) ;
		Assert.assertEquals( Integer.valueOf(100), carRecord.getDriver() ) ; // Not primitive type in model


	}

}
