/*
 * JUnit test case for bean Car
 * Created on 2017-01-30 ( Date ISO 2017-01-30 - Time 10:02:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package org.demo.basic.bean;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean Car
 * 
 * @author Telosys Tools Generator
 *
 */
public class CarTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class Car getters and setters ..." );
		
		Car car = new Car();

/*
		//--- Test setter/getter for field "id"  ( type : int )
		// System.out.println(" checking field id ..." );
		car.setId( intValue ) ;
		Assert.assertTrue( intValue == car.getId() ) ;

		//--- Test setter/getter for field "nom"  ( type : String )
		// System.out.println(" checking field nom ..." );
		car.setNom( stringValue ) ;
		Assert.assertTrue( stringValue.equals( car.getNom() ) ) ;

		//--- Test setter/getter for field "driver"  ( type : Integer )
		// System.out.println(" checking field driver ..." );
		car.setDriver( integerValue ) ;
		Assert.assertTrue( integerValue == car.getDriver() ) ;

*/


		//--- Test setter/getter for attribute "id"  ( type : int )
		car.setId( 100 ) ;
		Assert.assertEquals( 100, car.getId() ) ;


		//--- Test setter/getter for attribute "nom"  ( type : String )
		car.setNom( "A" ) ;
		Assert.assertEquals( "A", car.getNom() ) ;


		//--- Test setter/getter for attribute "driver"  ( type : Integer )
		car.setDriver( Integer.valueOf(100) ) ;
		Assert.assertEquals( Integer.valueOf(100), car.getDriver() ) ;


	}



}
