/*
 * Created on 2017-02-01 ( Date ISO 2017-02-01 - Time 11:10:33 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.fake;

import java.util.Hashtable;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import javax.inject.Named;


import org.demo.data.record.CarRecord;
import org.demo.persistence.CarPersistence;

@Named("CarPersistence")
public class CarPersistenceImplFake implements CarPersistence {

	private final static Map<String,CarRecord> map = new Hashtable<String,CarRecord>() ;

	private void checkNotNull(Object o) {
		if ( o == null ) {
			throw new IllegalArgumentException("Key element is null");
		}
	}

	/**
	 * Build the String key from this entity
     * @param id 
	 * @return the key
	 */
	private final String getKey( Integer id ) {
		checkNotNull(id);
		return ""  + id + "|"  ;
	}

	@Override
	public CarRecord findById(Integer id) {
		String key = getKey( id );
		return map.get(key);
	}

	@Override
	public List<CarRecord> findAll() {
		List<CarRecord> list = new LinkedList<CarRecord>();
		for ( CarRecord entity : map.values() ) {
			list.add(entity);
		}
		return list;
	}

	@Override
	public CarRecord save(CarRecord entity) {
		String key = getKey( entity.getId() );
		map.put(key, entity );
		return entity;
	}

	@Override
	public boolean update(CarRecord entity) {
		String key = getKey( entity.getId() );
		if ( map.get(key) == null ) {
			// Doesn't Exist => no update
			return false ;
		}
		else {
			// Exists => update
			map.put(key, entity );
			return true ;
		}
	}

	@Override
	public CarRecord create(CarRecord entity) {
		String key = getKey( entity.getId() );
		if ( map.get(key) == null ) {
			map.put(key, entity );
			return entity ;
		}
		else {
			throw new RuntimeException("CarRecord - Duplicate key : " + key );
		}
	}

	@Override
	public boolean deleteById(Integer id) {
		String key = getKey(id);
		CarRecord deleted = map.remove(key);
		return deleted != null ;
	}

	@Override
	public boolean delete(CarRecord entity) {
		String key = getKey( entity.getId() );
		CarRecord deleted = map.remove(key);
		return deleted != null ;
	}

}
