/*
 * Created on 2017-02-01 ( Date ISO 2017-02-01 - Time 11:10:33 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.fake;

import java.util.Hashtable;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import javax.inject.Named;


import org.demo.data.record.DriverRecord;
import org.demo.persistence.DriverPersistence;

@Named("DriverPersistence")
public class DriverPersistenceImplFake implements DriverPersistence {

	private final static Map<String,DriverRecord> map = new Hashtable<String,DriverRecord>() ;

	private void checkNotNull(Object o) {
		if ( o == null ) {
			throw new IllegalArgumentException("Key element is null");
		}
	}

	/**
	 * Build the String key from this entity
     * @param id 
	 * @return the key
	 */
	private final String getKey( Integer id ) {
		checkNotNull(id);
		return ""  + id + "|"  ;
	}

	@Override
	public DriverRecord findById(Integer id) {
		String key = getKey( id );
		return map.get(key);
	}

	@Override
	public List<DriverRecord> findAll() {
		List<DriverRecord> list = new LinkedList<DriverRecord>();
		for ( DriverRecord entity : map.values() ) {
			list.add(entity);
		}
		return list;
	}

	@Override
	public DriverRecord save(DriverRecord entity) {
		String key = getKey( entity.getId() );
		map.put(key, entity );
		return entity;
	}

	@Override
	public boolean update(DriverRecord entity) {
		String key = getKey( entity.getId() );
		if ( map.get(key) == null ) {
			// Doesn't Exist => no update
			return false ;
		}
		else {
			// Exists => update
			map.put(key, entity );
			return true ;
		}
	}

	@Override
	public DriverRecord create(DriverRecord entity) {
		String key = getKey( entity.getId() );
		if ( map.get(key) == null ) {
			map.put(key, entity );
			return entity ;
		}
		else {
			throw new RuntimeException("DriverRecord - Duplicate key : " + key );
		}
	}

	@Override
	public boolean deleteById(Integer id) {
		String key = getKey(id);
		DriverRecord deleted = map.remove(key);
		return deleted != null ;
	}

	@Override
	public boolean delete(DriverRecord entity) {
		String key = getKey( entity.getId() );
		DriverRecord deleted = map.remove(key);
		return deleted != null ;
	}

}
