/*
 * Created on 2017-01-30 ( Date ISO 2017-01-30 - Time 11:40:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.impl.jdbc;

import java.sql.SQLException;

import org.demo.data.record.CarRecord ;
import org.demo.persistence.impl.jdbc.commons.DAOTestUtil;

import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;


/**
 * JUnit tests for CarDAO
 * 
 * @author Telosys Tools
 *
 */
public class CarPersistenceJdbcTest {


	private static final String CREATE_TABLE = 
			 "CREATE TABLE Car ("
			+ "id INTEGER NOT NULL,"
			+ "nom VARCHAR(45) NOT NULL,"
			+ "driver INTEGER ,"
			+ "PRIMARY KEY(id)"
			+ ");"
			;

	@BeforeClass
	public static void init() {
		DAOTestUtil.initDatabase(CREATE_TABLE, "Car") ;
	}

	@Test
	public void testDAO() throws SQLException {
    	System.out.println("test CarDAO ");
    	CarPersistenceJdbc dao = new CarPersistenceJdbc();


    	Assert.assertTrue( dao.count() == 0 );

    	CarRecord car = new CarRecord();
		//--- Key values
		car.setId(100); // "id" : int
		//--- Other values
		car.setNom("A"); // "nom" : java.lang.String
		car.setDriver(Integer.valueOf(100)); // "driver" : java.lang.Integer

    	//--- INSERT
    	System.out.println("Insert : " + car );
    	dao.insert(car);
    	Assert.assertTrue( dao.exists(100) );
    	Assert.assertTrue( dao.count() == 1 );
    	Assert.assertTrue( dao.exists(car) );
    	
    	//--- FIND
    	System.out.println("Find..." );
    	CarRecord car2 = dao.findById(100);
    	Assert.assertNotNull(car2);
		Assert.assertTrue( car2.getId() == 100 ) ;
    	Assert.assertTrue( dao.exists(car2) ) ;
    	
    	//--- UPDATE
		//--- Change values
		car2.setNom("B"); // "nom" : java.lang.String
		car2.setDriver(Integer.valueOf(200)); // "driver" : java.lang.Integer
    	System.out.println("Update : " + car2 );
    	Assert.assertTrue( dao.update(car2) );
    	
    	//--- LOAD
    	CarRecord car3 = new CarRecord();
    	car3.setId(100);
    	Assert.assertTrue( dao.load(car3) );
    	System.out.println("Loaded : " + car3 );
		Assert.assertEquals(car2.getNom(), car3.getNom() ); 
		Assert.assertEquals(car2.getDriver(), car3.getDriver() ); 


    	car3.setId(300);
    	Assert.assertFalse( dao.load(car3) );
    	
    	//--- DELETE
    	System.out.println("Delete : " + car2 );
    	Assert.assertTrue( dao.delete(car2) ); // Delete #1 : OK
    	Assert.assertFalse( dao.delete(car2) ); // Nothing (already deleted)
    	Assert.assertFalse( dao.deleteById(100) ); // Nothing (already deleted)

    	Assert.assertTrue( dao.count() == 0 );
    	Assert.assertFalse( dao.exists(100) ) ;
    	Assert.assertFalse( dao.exists(car2) ) ;
    	car2 = dao.findById(100);
    	Assert.assertNull( car2 );
    	
    	System.out.println("Normal end of DAO test." );
	}

}
