/*
 * JUnit test case for bean Car
 * Created on 2017-01-30 ( Date ISO 2017-01-30 - Time 10:21:30 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package org.demo.data.domain;


import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean Car
 * 
 * @author Telosys Tools Generator
 *
 */
public class CarTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class Car getters and setters ..." );
		
		Car car = new Car();



		//--- Test setter/getter for attribute "id"  ( type : int )
		car.setId( 100 ) ;
		Assert.assertEquals( 100, car.getId() ) ;

		//--- Test setter/getter for attribute "nom"  ( type : String )
		car.setNom( "A" ) ;
		Assert.assertEquals( "A", car.getNom() ) ;

	}



}
