/*
 * JUnit test case for bean Driver
 * Created on 2017-01-30 ( Date ISO 2017-01-30 - Time 10:21:30 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package org.demo.data.domain;


import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean Driver
 * 
 * @author Telosys Tools Generator
 *
 */
public class DriverTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class Driver getters and setters ..." );
		
		Driver driver = new Driver();



		//--- Test setter/getter for attribute "id"  ( type : int )
		driver.setId( 100 ) ;
		Assert.assertEquals( 100, driver.getId() ) ;

		//--- Test setter/getter for attribute "nom"  ( type : String )
		driver.setNom( "A" ) ;
		Assert.assertEquals( "A", driver.getNom() ) ;

	}



}
