/*
 * Created on 2017-01-30 ( Date ISO 2017-01-30 - Time 10:04:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.data.record.listitem;

import org.demo.data.record.DriverRecord;
import org.demo.commons.ListItem;

public class DriverListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public DriverListItem(DriverRecord driver) {
		super();

		this.value = ""
			 + driver.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = driver.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
