/*
 * JUnit test case for Driver caching service
 * Created on 2017-01-30 ( Date ISO 2017-01-30 - Time 10:02:24 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package org.demo.basic.cache;

import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.demo.basic.bean.Driver ;

import org.junit.Test;

/**
 * JUnit test case for Driver caching service
 * 
 * @author Telosys Tools Generator
 *
 */
public class DriverCacheTest 
{
	//protected static final java.util.Date now = new java.util.Date();

	private final static void populate(Driver driver) {
		driver.setId( 100 ) ;
		driver.setNom( "A" ) ;
	}

	@Test
	public void testPutGetRemove() {
		
		System.out.println("Testing class DriverCache ..." );
		
		Driver driver = new Driver();
		populate(driver);
		System.out.println("Entity populated : " + driver );
		
		DriverCache.putDriver(driver) ;	// Store in cache	
		
		Driver driver2 = DriverCache.getDriver( driver.getId() );
		assertTrue( driver == driver2 ) ; // Same instance
		
		DriverCache.removeDriver(  driver.getId() ) ; // Remove from cache	
		
		Driver driver3 = DriverCache.getDriver( driver.getId() );
		assertTrue( null == driver3 ) ; // Not in cache
		assertNull(driver3); // Not in cache

	}
}
