/*
 * Very basic JavaBean cache
 * Created on 2017-01-30 ( Date ISO 2017-01-30 - Time 10:02:23 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
package org.demo.basic.cache;

import java.util.Hashtable;
import java.util.Map;

import org.demo.basic.bean.Car ;

/**
 * Very basic cache for Car instances (just for the Telosys Tools demo)
 * 
 * @author Telosys Tools Generator
 *
 */
public class CarCache
{
	private final static Map<String,Car> cache = new Hashtable<String,Car>() ;
	
	/**
	 * Build the cache key from the Primary Key field(s)
     * @param id 
	 * @return the key
	 */
	private final static String getKey( int id ) {
		return ""  + id  ;
	}

	/**
	 * Put the given Car instance in the cache
	 * @param Car instance to be stored
	 */
	public final static void putCar(Car car ) {
		String key = getKey( car.getId() ) ;
		cache.put(key, car );
	}
	
	/**
	 * Get the Car instance for the given primary key
     * @param id 
	 * @return the Car instance (or null if none)
	 */
	public final static Car getCar( int id ) {
		String key = getKey( id ) ;
		return cache.get(key);
	}

	/**
	 * Removes the Car associated with the given primary key
     * @param id 
	 */
	public final static void removeCar ( int id ) {
		String key = getKey( id ) ;
		cache.remove(key);
	}
	
	/**
	 * Removes the given Car from the cache using its primary key
	 * @param Car instance to be removed
	 */
	public final static void removeCar (Car car ) { 
		String key = getKey( car.getId() ) ;
		cache.remove(key);
	}

}
